// Generated by drizzle-cube dbt generate.
// Source: manifest=tests/fixtures/dbt/postgres-simple/manifest.json, catalog=tests/fixtures/dbt/postgres-simple/catalog.json, dialect=postgres.
// Do not edit manually; change dbt metadata or generator config instead.

import { integer, numeric, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const customers = pgTable("customers", {
  id: integer("id").primaryKey(),
  name: text("name"),
  organisationId: integer("organisation_id").notNull(),
  createdAt: timestamp("created_at"),
})

export const orders = pgTable("orders", {
  id: integer("id").primaryKey(),
  customerId: integer("customer_id"),
  organisationId: integer("organisation_id").notNull(),
  amount: numeric("amount"),
  status: text("status"),
  orderedAt: timestamp("ordered_at"),
})

export const schema = {
  customers,
  orders,
}

export type Schema = typeof schema
