// Generated by drizzle-cube dbt generate.
import { defineCube } from 'drizzle-cube/server'
import type { BaseQueryDefinition } from 'drizzle-cube/server'
import { customers } from '../schema.js'

export const customersCube = defineCube("Customers", {
  title: "Customers",
  description: "Customer dimension model.",
  sql: (): BaseQueryDefinition => ({ from: customers }),

  dimensions: {
    id: {
      name: "id",
      title: "Id",
      description: "Customer identifier.",
      type: "number",
      sql: customers.id,
      primaryKey: true
    },
    name: {
      name: "name",
      title: "Name",
      description: "Customer name.",
      type: "string",
      sql: customers.name
    },
    organisationId: {
      name: "organisationId",
      title: "Organisation Id",
      description: "Tenant organisation identifier.",
      type: "number",
      sql: customers.organisationId
    },
    createdAt: {
      name: "createdAt",
      title: "Created At",
      description: "Customer creation timestamp.",
      type: "time",
      sql: customers.createdAt
    },
  },

  measures: {
    count: {
      name: "count",
      title: "Count",
      type: "countDistinct",
      sql: customers.id
    },
  },
})
