/**
 * Shared helpers for the deterministic TypeScript emitters.
 */

export interface HeaderInfo {
  manifestPath: string
  catalogPath: string
}

/** The generated-file ownership header placed at the top of every emitted file. */
export function generatedHeader(info: HeaderInfo): string {
  return [
    '// Generated by drizzle-cube dbt generate.',
    `// Source: manifest=${info.manifestPath}, catalog=${info.catalogPath}, dialect=postgres.`,
    '// Do not edit manually; change dbt metadata or generator config instead.'
  ].join('\n')
}

/** Quote a string as a single-quoted TS literal, escaping as needed. */
export function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

/** Sort a string array ascending (stable, locale-independent) and de-duplicate. */
export function sortedUnique(values: string[]): string[] {
  return [...new Set(values)].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
}
