import type { DimensionType, MeasureFormat, MeasureType } from '../../server/types/core.js'

export const GENERATED_HEADER_PREFIX = '// Generated by drizzle-cube dbt generate.'

export interface DbtManifest {
  nodes: Record<string, DbtManifestNode>
}

export interface DbtManifestColumn extends Record<string, unknown> {
  name?: string
  description?: string
  data_type?: string
  tests?: unknown[]
  meta?: Record<string, unknown>
}

export interface DbtManifestNode extends Record<string, unknown> {
  unique_id?: string
  resource_type?: string
  name?: string
  alias?: string
  schema?: string
  database?: string
  description?: string
  config?: Record<string, unknown>
  columns?: Record<string, DbtManifestColumn>
  meta?: Record<string, unknown>
  constraints?: Array<Record<string, unknown>>
  test_metadata?: { name?: string; kwargs?: Record<string, unknown> }
  depends_on?: { nodes?: string[] }
  attached_node?: string
  column_name?: string
}

export interface DbtCatalog {
  nodes: Record<string, DbtCatalogNode>
}

export interface DbtCatalogColumn extends Record<string, unknown> {
  name?: string
  type?: string
  index?: number
  comment?: string
}

export interface DbtCatalogNode extends Record<string, unknown> {
  unique_id?: string
  metadata?: Record<string, unknown>
  columns?: Record<string, DbtCatalogColumn>
}

export type DbtTestNode = DbtManifestNode

export type SecurityConfig =
  | { mode: 'none' }
  | { mode: 'column'; column: string; context: string }

export interface GeneratorWarning {
  message: string
}

export interface ExplicitMeasureConfig {
  name: string
  type: MeasureType
  column?: string
  title?: string
  description?: string
  format?: MeasureFormat
}

export interface GeneratorConfig {
  security?: SecurityConfig
  models?: Record<string, {
    cubeName?: string
    tableExportName?: string
    columns?: Record<string, {
      propertyName?: string
      dimensionName?: string
      dimensionType?: DimensionType
    }>
    measures?: ExplicitMeasureConfig[]
  }>
  typeOverrides?: Record<string, {
    drizzleBuilder: string
    dimensionType?: DimensionType
  }>
}

export interface DbtGenerateOptions {
  manifestPath: string
  catalogPath: string
  dialect: 'postgres'
  outDir: string
  config: GeneratorConfig
  security: SecurityConfig
}

export interface GeneratedColumn {
  dbName: string
  propertyName: string
  dimensionName: string
  title: string
  description?: string
  catalogType: string
  drizzleBuilder: string
  drizzleImport: string
  dimensionType?: DimensionType
  primaryKey: boolean
  notNull: boolean
}

export interface GeneratedMeasure {
  name: string
  title: string
  type: MeasureType
  columnPropertyName?: string
  description?: string
  format?: MeasureFormat
}

export interface GeneratedJoin {
  sourceModelId: string
  targetModelId: string
  targetCubeName: string
  sourceColumnPropertyName: string
  targetColumnPropertyName: string
  targetTableExportName: string
  relationship: 'belongsTo'
}

export interface GeneratedModel {
  uniqueId: string
  dbtName: string
  relationName: string
  schemaName?: string
  databaseName?: string
  tableExportName: string
  cubeName: string
  cubeVarName: string
  fileName: string
  title: string
  description?: string
  columns: GeneratedColumn[]
  primaryKeyColumn?: GeneratedColumn
  joins: GeneratedJoin[]
  measures: GeneratedMeasure[]
}

export interface GeneratedFile {
  path: string
  content: string
}
