/**
 * Filesystem writer for generated dbt cubes/schema.
 *
 * The only module that performs filesystem writes for the generator. All
 * returned arrays are sorted with `localeCompare` for deterministic output.
 */

import { readdir, mkdir, writeFile, stat } from 'node:fs/promises'
import { join, normalize, resolve, sep } from 'node:path'
import type { GeneratedFile, WriteResult } from './types.js'

/** Ownership header stamped on every generated file. */
export const GENERATED_HEADER = '// Generated by drizzle-cube dbt generate.'

export interface WriteOptions {
  outDir: string
  dryRun: boolean
  check: boolean
  force: boolean
}

const emptyResult = (): WriteResult => ({
  created: [],
  updated: [],
  deleted: [],
  conflicts: [],
  missing: [],
  orphaned: [],
  drift: false,
})

/** Convert a POSIX relative path to a platform-native, traversal-safe absolute path. */
function safeResolve(outDir: string, relativePosix: string): string {
  const native = relativePosix.split('/').join(sep)
  const base = resolve(outDir)
  const target = normalize(resolve(base, native))
  if (target !== base && !target.startsWith(`${base}${sep}`)) {
    throw new Error(
      `Refusing to write outside output directory: '${relativePosix}' resolves outside '${outDir}'.`,
    )
  }
  return target
}

/** Convert an absolute file path back to an out-dir-relative POSIX path. */
function toRelativePosix(outDir: string, absPath: string): string {
  const base = resolve(outDir)
  const rel = absPath.startsWith(`${base}${sep}`)
    ? absPath.slice(`${base}${sep}`.length)
    : absPath
  return rel.split(sep).join('/')
}

function isGeneratedContent(content: string): boolean {
  return content.startsWith(GENERATED_HEADER)
}

async function fileExists(absPath: string): Promise<boolean> {
  try {
    await stat(absPath)
    return true
  } catch {
    return false
  }
}

/** Recursively collect files under `outDir`; returns absolute paths. */
async function walkFiles(dir: string): Promise<string[]> {
  let entries: string[]
  try {
    entries = await readdir(dir)
  } catch {
    return []
  }
  const results: string[] = []
  for (const entry of entries) {
    const abs = join(dir, entry)
    let info
    try {
      info = await stat(abs)
    } catch {
      continue
    }
    if (info.isDirectory()) {
      results.push(...(await walkFiles(abs)))
    } else {
      results.push(abs)
    }
  }
  return results
}

/** Return the set of out-dir-relative POSIX paths of existing generated files. */
async function findExistingGeneratedFiles(outDir: string): Promise<Set<string>> {
  const absFiles = await walkFiles(outDir)
  const generated = new Set<string>()
  for (const abs of absFiles) {
    let content: string
    try {
      const { readFile } = await import('node:fs/promises')
      content = await readFile(abs, 'utf-8')
    } catch {
      continue
    }
    if (isGeneratedContent(content)) {
      generated.add(toRelativePosix(outDir, abs))
    }
  }
  return generated
}

function sortStrings(arr: string[]): string[] {
  return [...arr].sort((a, b) => a.localeCompare(b))
}

// ---------------------------------------------------------------------------
// Modes
// ---------------------------------------------------------------------------

async function checkMode(
  files: GeneratedFile[],
  outDir: string,
): Promise<WriteResult> {
  const result = emptyResult()
  const expected = new Map(files.map((f) => [f.path, f.content]))
  const existing = await findExistingGeneratedFiles(outDir)

  for (const file of files) {
    const abs = safeResolve(outDir, file.path)
    if (!(await fileExists(abs))) {
      result.missing.push(file.path)
      continue
    }
    const { readFile } = await import('node:fs/promises')
    const onDisk = await readFile(abs, 'utf-8')
    if (onDisk !== file.content) {
      result.updated.push(file.path)
    }
  }

  for (const existingPath of existing) {
    if (!expected.has(existingPath)) {
      result.orphaned.push(existingPath)
    }
  }

  result.missing = sortStrings(result.missing)
  result.orphaned = sortStrings(result.orphaned)
  result.updated = sortStrings(result.updated)
  result.drift = result.updated.length > 0 || result.missing.length > 0 || result.orphaned.length > 0
  return result
}

async function dryRunMode(
  files: GeneratedFile[],
  outDir: string,
  force: boolean,
): Promise<WriteResult> {
  const result = emptyResult()
  const expected = new Set(files.map((f) => f.path))
  const existing = await findExistingGeneratedFiles(outDir)

  for (const file of files) {
    const abs = safeResolve(outDir, file.path)
    if (!(await fileExists(abs))) {
      result.created.push(file.path)
      continue
    }
    const { readFile } = await import('node:fs/promises')
    const onDisk = await readFile(abs, 'utf-8')
    if (isGeneratedContent(onDisk)) {
      if (onDisk !== file.content || force) {
        result.updated.push(file.path)
      }
    } else if (force) {
      result.updated.push(file.path)
    } else {
      result.conflicts.push(file.path)
    }
  }

  for (const existingPath of existing) {
    if (!expected.has(existingPath)) {
      result.orphaned.push(existingPath)
    }
  }

  result.deleted = sortStrings(result.orphaned)
  result.created = sortStrings(result.created)
  result.updated = sortStrings(result.updated)
  result.conflicts = sortStrings(result.conflicts)
  result.orphaned = sortStrings(result.orphaned)
  return result
}

async function normalMode(
  files: GeneratedFile[],
  outDir: string,
  force: boolean,
): Promise<WriteResult> {
  const result = emptyResult()
  const expected = new Set(files.map((f) => f.path))
  const existing = await findExistingGeneratedFiles(outDir)

  for (const file of files) {
    const abs = safeResolve(outDir, file.path)
    if (!(await fileExists(abs))) {
      await mkdir(join(abs, '..'), { recursive: true })
      await writeFile(abs, file.content, 'utf-8')
      result.created.push(file.path)
      continue
    }
    const { readFile } = await import('node:fs/promises')
    const onDisk = await readFile(abs, 'utf-8')
    if (isGeneratedContent(onDisk)) {
      if (onDisk !== file.content || force) {
        await writeFile(abs, file.content, 'utf-8')
        result.updated.push(file.path)
      }
    } else if (force) {
      await writeFile(abs, file.content, 'utf-8')
      result.updated.push(file.path)
    } else {
      result.conflicts.push(file.path)
    }
  }

  // Delete stale generated-header files no longer expected.
  const { unlink } = await import('node:fs/promises')
  for (const existingPath of existing) {
    if (!expected.has(existingPath)) {
      const abs = safeResolve(outDir, existingPath)
      await unlink(abs)
      result.deleted.push(existingPath)
    }
  }

  result.created = sortStrings(result.created)
  result.updated = sortStrings(result.updated)
  result.deleted = sortStrings(result.deleted)
  result.conflicts = sortStrings(result.conflicts)
  return result
}

/**
 * Write (or plan/check) generated files. Selects mode from `options`:
 * `--check` writes nothing and reports full expected-vs-existing drift;
 * `--dry-run` writes nothing and reports planned changes; otherwise writes
 * files and deletes stale generated files.
 */
export async function writeGeneratedOutput(
  files: GeneratedFile[],
  options: WriteOptions,
): Promise<WriteResult> {
  if (options.check) return checkMode(files, options.outDir)
  if (options.dryRun) return dryRunMode(files, options.outDir, options.force)
  return normalMode(files, options.outDir, options.force)
}
