/**
 * Write generated files to disk with ownership checks, drift detection, and
 * stale-file cleanup. This is the only module that performs filesystem writes
 * for the generator.
 *
 * Modes:
 *  - normal: create/update generated-header files; refuse to overwrite
 *    non-generated files unless `--force`; delete stale generated files.
 *  - `--dry-run`: write/delete nothing; report planned operations.
 *  - `--check`: write/delete nothing; report drift (changed/missing/
 *    conflicting/orphaned) including the affected file paths. Removals
 *    count as drift.
 */
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { normalize, resolve, sep } from 'node:path'
import type { GeneratedFile, WriteResult } from './types.js'

/** Ownership header present at the top of every generated file. */
export const GENERATED_HEADER = '// Generated by drizzle-cube dbt generate.'

export interface WriteOptions {
  outDir: string
  dryRun: boolean
  check: boolean
  force: boolean
}

/**
 * Resolve an out-dir-relative POSIX path to an absolute OS path, guarding
 * against path traversal. Throws if the resolved path escapes `outDir`.
 */
function safeResolve(outDir: string, relativePosix: string): string {
  const base = resolve(outDir)
  // Convert POSIX separators to platform separators before joining.
  const platformRel = relativePosix.split('/').join(sep)
  const target = normalize(resolve(base, platformRel))
  if (target !== base && !target.startsWith(base + sep)) {
    throw new Error(
      `Refusing to write outside output directory: '${relativePosix}' resolves outside '${outDir}'.`,
    )
  }
  return target
}

/** True when file content begins with the generated ownership header. */
function isGeneratedContent(content: string): boolean {
  return content.startsWith(GENERATED_HEADER)
}

/** True when an error is a filesystem ENOENT (file/directory not found). */
function isENOENT(err: unknown): boolean {
  return (
    typeof err === 'object' &&
    err !== null &&
    (err as { code?: unknown }).code === 'ENOENT'
  )
}

/** Read a file's text, or `null` if it does not exist. */
async function readIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf-8')
  } catch (err) {
    if (isENOENT(err)) return null
    throw err
  }
}

/**
 * Walk `outDir` and return the set of relative POSIX paths of files that
 * begin with the generated ownership header. Used for stale-file detection.
 */
async function findExistingGeneratedFiles(outDir: string): Promise<Set<string>> {
  const { readdir } = await import('node:fs/promises')
  const base = resolve(outDir)
  const found = new Set<string>()

  async function walk(dir: string): Promise<void> {
    let entries
    try {
      entries = await readdir(dir, { withFileTypes: true })
    } catch (err) {
      if (isENOENT(err)) return
      throw err
    }
    for (const entry of entries) {
      const full = resolve(dir, entry.name)
      if (entry.isDirectory()) {
        await walk(full)
      } else if (entry.isFile()) {
        const content = await readIfExists(full)
        if (content && isGeneratedContent(content)) {
          const rel = full.slice(base.length + 1).split(sep).join('/')
          found.add(rel)
        }
      }
    }
  }

  await walk(base)
  return found
}

/** Classify a single expected file against the existing on-disk state. */
type FileKind = 'create' | 'update' | 'conflict' | 'unchanged'

async function classifyFile(
  outDir: string,
  file: GeneratedFile,
  force: boolean,
): Promise<{ kind: FileKind; existing: string | null }> {
  const abs = safeResolve(outDir, file.path)
  const existing = await readIfExists(abs)
  if (existing === null) return { kind: 'create', existing: null }
  if (isGeneratedContent(existing)) {
    return { kind: existing === file.content ? 'unchanged' : 'update', existing }
  }
  return { kind: force ? 'update' : 'conflict', existing }
}

/** Build the `WriteResult` for check mode without writing anything. */
async function checkMode(
  files: GeneratedFile[],
  options: WriteOptions,
): Promise<WriteResult> {
  const expected = new Set(files.map((f) => f.path))
  const existing = await findExistingGeneratedFiles(options.outDir)

  const changed: string[] = []
  const missing: string[] = []
  for (const file of files) {
    const { kind } = await classifyFile(options.outDir, file, false)
    if (kind === 'create') missing.push(file.path)
    else if (kind === 'update') changed.push(file.path)
    else if (kind === 'conflict') changed.push(file.path)
  }
  const orphaned = Array.from(existing)
    .filter((p) => !expected.has(p))
    .sort((a, b) => a.localeCompare(b))

  const drift = changed.length > 0 || missing.length > 0 || orphaned.length > 0
  return {
    created: [],
    updated: changed.sort((a, b) => a.localeCompare(b)),
    deleted: [],
    conflicts: [],
    missing: missing.sort((a, b) => a.localeCompare(b)),
    orphaned,
    drift,
  }
}

/** Build the `WriteResult` for dry-run mode without writing anything. */
async function dryRunMode(
  files: GeneratedFile[],
  options: WriteOptions,
): Promise<WriteResult> {
  const expected = new Set(files.map((f) => f.path))
  const existing = await findExistingGeneratedFiles(options.outDir)

  const created: string[] = []
  const updated: string[] = []
  const conflicts: string[] = []
  for (const file of files) {
    const { kind } = await classifyFile(options.outDir, file, options.force)
    if (kind === 'create') created.push(file.path)
    else if (kind === 'update') updated.push(file.path)
    else if (kind === 'conflict') conflicts.push(file.path)
  }
  const deleted = Array.from(existing)
    .filter((p) => !expected.has(p))
    .sort((a, b) => a.localeCompare(b))

  return {
    created: created.sort((a, b) => a.localeCompare(b)),
    updated: updated.sort((a, b) => a.localeCompare(b)),
    deleted,
    conflicts: conflicts.sort((a, b) => a.localeCompare(b)),
    missing: [],
    orphaned: deleted,
    drift: false,
  }
}

/** Normal mode: write/update files and delete stale generated files. */
async function normalMode(
  files: GeneratedFile[],
  options: WriteOptions,
): Promise<WriteResult> {
  const expected = new Set(files.map((f) => f.path))
  const existing = await findExistingGeneratedFiles(options.outDir)

  const created: string[] = []
  const updated: string[] = []
  const conflicts: string[] = []
  for (const file of files) {
    const abs = safeResolve(options.outDir, file.path)
    const { kind } = await classifyFile(options.outDir, file, options.force)
    if (kind === 'conflict') {
      conflicts.push(file.path)
      continue
    }
    await mkdir(resolve(abs, '..'), { recursive: true })
    await writeFile(abs, file.content, 'utf-8')
    if (kind === 'create') created.push(file.path)
    else updated.push(file.path)
  }

  const deleted: string[] = []
  for (const stale of Array.from(existing).sort((a, b) => a.localeCompare(b))) {
    if (expected.has(stale)) continue
    const abs = safeResolve(options.outDir, stale)
    await rm(abs, { force: true })
    deleted.push(stale)
  }

  return {
    created: created.sort((a, b) => a.localeCompare(b)),
    updated: updated.sort((a, b) => a.localeCompare(b)),
    deleted: deleted.sort((a, b) => a.localeCompare(b)),
    conflicts: conflicts.sort((a, b) => a.localeCompare(b)),
    missing: [],
    orphaned: [],
    drift: false,
  }
}

/**
 * Write generated files to `outDir` according to the selected mode.
 *
 * - `--check`: no writes; returns `drift: true` if the expected set differs
 *   from the existing generated set (changed/missing/orphaned). The
 *   returned `missing`, `orphaned`, and `updated` arrays list the affected
 *   file paths so callers can surface what drifted.
 * - `--dry-run`: no writes; reports planned creates/updates/deletes/conflicts.
 * - normal: writes files, refuses non-generated conflicts (unless `--force`),
 *   and deletes stale generated-header files no longer in the expected set.
 */
export async function writeGeneratedOutput(
  files: GeneratedFile[],
  options: WriteOptions,
): Promise<WriteResult> {
  if (options.check) return checkMode(files, options)
  if (options.dryRun) return dryRunMode(files, options)
  return normalMode(files, options)
}
