import { mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, resolve, sep } from 'node:path'
import type { GeneratedFile, WriteResult } from './types.js'

export const GENERATED_HEADER = '// Generated by drizzle-cube dbt generate.'

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path)
    return true
  } catch {
    return false
  }
}

function assertSafePath(outDir: string, relativePath: string): string {
  if (relativePath.startsWith('/') || relativePath.includes('..')) throw new Error(`Refusing unsafe generated path '${relativePath}'.`)
  const root = resolve(outDir)
  const fullPath = resolve(root, relativePath)
  if (fullPath !== root && !fullPath.startsWith(`${root}${sep}`)) throw new Error(`Refusing to write outside output directory: ${relativePath}`)
  return fullPath
}

async function listFiles(root: string, current = ''): Promise<string[]> {
  const directory = resolve(root, current)
  if (!(await exists(directory))) return []
  const entries = await readdir(directory, { withFileTypes: true })
  const files: string[] = []
  for (const entry of entries) {
    const child = current ? `${current}/${entry.name}` : entry.name
    if (entry.isDirectory()) files.push(...await listFiles(root, child))
    if (entry.isFile()) files.push(child)
  }
  return files
}

async function generatedFiles(outDir: string): Promise<string[]> {
  const files = await listFiles(outDir)
  const result: string[] = []
  for (const file of files) {
    const content = await readFile(assertSafePath(outDir, file), 'utf8')
    if (content.startsWith(GENERATED_HEADER)) result.push(file)
  }
  return result
}

function emptyResult(): WriteResult {
  return { created: [], updated: [], unchanged: [], deleted: [], conflicts: [], warnings: [] }
}

async function classifyFile(outDir: string, file: GeneratedFile, force: boolean, result: WriteResult): Promise<void> {
  const target = assertSafePath(outDir, file.path)
  if (!(await exists(target))) {
    result.created.push(file.path)
    return
  }
  const current = await readFile(target, 'utf8')
  if (!current.startsWith(GENERATED_HEADER) && !force) {
    result.conflicts.push(file.path)
    return
  }
  if (!current.startsWith(GENERATED_HEADER) && force) {
    result.warnings.push({ code: 'forced_overwrite', message: `Overwriting non-generated file '${file.path}' because --force was provided.` })
  }
  if (current === file.content) result.unchanged.push(file.path)
  else result.updated.push(file.path)
}

async function plan(files: GeneratedFile[], options: { outDir: string; force: boolean }): Promise<WriteResult> {
  const result = emptyResult()
  for (const file of files) await classifyFile(options.outDir, file, options.force, result)
  const expected = new Set(files.map((file) => file.path))
  for (const file of await generatedFiles(options.outDir)) {
    if (!expected.has(file)) {
      result.deleted.push(file)
      result.warnings.push({ code: 'stale_generated_file', message: `Stale generated file '${file}' is no longer expected.` })
    }
  }
  return result
}

function driftMessage(result: WriteResult): string {
  const changes = [
    ...result.created.map((file) => `missing: ${file}`),
    ...result.updated.map((file) => `changed: ${file}`),
    ...result.deleted.map((file) => `stale: ${file}`),
    ...result.conflicts.map((file) => `conflict: ${file}`)
  ]
  return `Generated dbt output is not up to date:\n${changes.join('\n')}`
}

export async function writeGeneratedOutput(files: GeneratedFile[], options: { outDir: string; dryRun: boolean; check: boolean; force: boolean }): Promise<WriteResult> {
  for (const file of files) assertSafePath(options.outDir, file.path)
  const result = await plan(files, options)
  if (options.check) {
    if (result.created.length || result.updated.length || result.deleted.length || result.conflicts.length) throw new Error(driftMessage(result))
    return result
  }
  if (options.dryRun) return result
  if (result.conflicts.length) throw new Error(`Refusing to overwrite non-generated files: ${result.conflicts.join(', ')}. Use --force to replace them.`)

  for (const file of files) {
    if (!file.content.startsWith(GENERATED_HEADER)) throw new Error(`Generated file '${file.path}' is missing the ownership header.`)
    const target = assertSafePath(options.outDir, file.path)
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, file.content)
  }
  for (const file of result.deleted) await rm(assertSafePath(options.outDir, file), { force: true })
  return result
}
