// Generated by drizzle-cube dbt generate.

import { CustomersCube } from './cubes/customers'
import { OrdersCube } from './cubes/orders'

export { CustomersCube } from './cubes/customers'
export { OrdersCube } from './cubes/orders'

export { schema } from './schema'

export const allCubes = [
  CustomersCube,
  OrdersCube
]
