// Generated by drizzle-cube dbt generate.

import { CustomersCube } from './cubes/customers.js'
import { OrderLinesCube } from './cubes/order-lines.js'
import { OrdersCube } from './cubes/orders.js'

export { CustomersCube } from './cubes/customers.js'
export { OrderLinesCube } from './cubes/order-lines.js'
export { OrdersCube } from './cubes/orders.js'

export { schema } from './schema.js'

export const allCubes = [
  CustomersCube,
  OrderLinesCube,
  OrdersCube
]
