// Generated by drizzle-cube dbt generate.
// Source: manifest=tests/fixtures/dbt/postgres-simple/manifest.json, catalog=tests/fixtures/dbt/postgres-simple/catalog.json, dialect=postgres.
// Root index for generated cubes. Re-run 'drizzle-cube dbt generate' to update.

import { customersCube } from './cubes/customers.js'
import { orderLinesCube } from './cubes/order-lines.js'
import { ordersCube } from './cubes/orders.js'

export { customersCube }
export { orderLinesCube }
export { ordersCube }

export const allCubes = [
  customersCube,
  orderLinesCube,
  ordersCube,
]
