// Generated by drizzle-cube dbt generate.

import { pgTable, boolean, integer, numeric, text, timestamp } from 'drizzle-orm/pg-core'

export const customers = pgTable('customers', {
    id: integer('id').notNull().primaryKey(),
    organisationId: integer('organisation_id'),
    name: text('name'),
    active: boolean('active')
})

export const orders = pgTable('orders', {
    id: integer('id').notNull().primaryKey(),
    organisationId: integer('organisation_id'),
    customerId: integer('customer_id'),
    status: text('status'),
    amount: numeric('amount'),
    createdAt: timestamp('created_at')
})

export const schema = {
  customers,
  orders
}

export type Schema = typeof schema
