// Generated by drizzle-cube dbt generate.
// Source: manifest=manifest.json catalog=catalog.json dialect=postgres
// To regenerate, run: npx drizzle-cube dbt generate --manifest manifest.json --catalog catalog.json --dialect postgres

import { pgTable, boolean, integer, numeric, text, timestamp } from 'drizzle-orm/pg-core'

export const Customers = pgTable('customers', {
  id: integer('id').primaryKey(), // Customer primary key.
  organisationId: integer('organisation_id'), // Tenant scope.
  name: text('name'), // Customer display name.
  status: text('status'),
  createdAt: timestamp('created_at'),
  active: boolean('active'),
})

export const OrderLines = pgTable('order_lines', {
  orderId: integer('order_id').primaryKey(), // Composite PK part 1.
  lineNumber: integer('line_number').primaryKey(), // Composite PK part 2.
  organisationId: integer('organisation_id'), // Tenant scope.
  quantity: integer('quantity'),
  sku: text('sku'),
  amount: numeric('amount'),
  createdAt: timestamp('created_at'),
})

export const Orders = pgTable('orders', {
  id: integer('id').primaryKey(), // Order primary key.
  organisationId: integer('organisation_id'), // Tenant scope.
  customerId: integer('customer_id'), // References customers.id.
  amount: numeric('amount'), // Order total.
  status: text('status'),
  createdAt: timestamp('created_at'),
  active: boolean('active'),
})

export const schema = {
  Customers,
  OrderLines,
  Orders,
}

export type Schema = typeof schema
