// Generated by drizzle-cube dbt generate.

import { pgSchema, primaryKey, boolean, integer, numeric, text, time, timestamp, uuid } from 'drizzle-orm/pg-core'

const analyticsSchema = pgSchema('analytics')

export const customers = analyticsSchema.table('customers', {
    id: integer('id').notNull().primaryKey(),
    organisationId: integer('organisation_id').notNull(),
    name: text('name'),
    active: boolean('active'),
    signedUpAt: timestamp('signed_up_at', { withTimezone: true }),
    externalRef: uuid('external_ref'),
    parentCustomerId: integer('parent_customer_id')
})

export const orderLines = analyticsSchema.table('order_lines', {
    orderId: integer('order_id'),
    lineNumber: integer('line_number'),
    organisationId: integer('organisation_id'),
    count: integer('count')
}, (table) => [
  primaryKey({ columns: [table.orderId, table.lineNumber] })
])

export const orders = analyticsSchema.table('orders', {
    id: integer('id').notNull().primaryKey(),
    organisationId: integer('organisation_id'),
    customerId: integer('customer_id'),
    referredByCustomerId: integer('referred_by_customer_id'),
    status: text('status'),
    amount: numeric('amount'),
    createdAt: timestamp('created_at'),
    deliveryTime: time('delivery_time')
})

export const schema = {
  customers,
  orderLines,
  orders
}

export type Schema = typeof schema
