#:schema node_modules/wrangler/config-schema.json
name = "drizzle-cube-help"
main = "dist/worker.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

# Static assets binding
[assets]
directory = "dist"
binding = "ASSETS"

# Worker configuration
[env.production]
name = "drizzle-cube-help"

[env.staging]
name = "drizzle-cube-help-staging"