/**
 * Post-build script: reads dist/mcp-app/mcp-app.html and writes
 * src/adapters/mcp-app-html.ts as an exported string constant.
 *
 * Run after build:mcp-app, before build:adapters.
 */

import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const htmlPath = join(root, 'dist/mcp-app/mcp-app.html')
const outPath = join(root, 'src/adapters/mcp-app-html.ts')

const html = readFileSync(htmlPath, 'utf-8')

const source = `// AUTO-GENERATED by scripts/generate-mcp-app-html.ts — do not edit
// Built from dist/mcp-app/mcp-app.html (${(html.length / 1024).toFixed(0)}KB)
export const mcpAppHtml: string = ${JSON.stringify(html)}
`

writeFileSync(outPath, source, 'utf-8')
console.log(`Generated ${outPath} (${(html.length / 1024).toFixed(0)}KB)`)
