/**
 * Post-build script: reads dist/mcp-app/mcp-app.html and writes it
 * to src/mcp-app/generated-html.ts as an exported string constant.
 *
 * This keeps the large HTML blob out of mcp-transport.ts while still
 * allowing bundlers to include it without tree-shaking issues.
 *
 * Run after build:mcp-app, before build:adapters.
 */

import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const htmlPath = join(root, 'dist/mcp-app/mcp-app.html')
const outputPath = join(root, 'src/mcp-app/generated-html.ts')

const html = readFileSync(htmlPath, 'utf-8')

const output = [
  '// Auto-generated by scripts/generate-mcp-app-html.ts — DO NOT EDIT',
  '// Run `npm run build:mcp-app` to regenerate',
  `export const mcpAppHtml: string = ${JSON.stringify(html)}`,
  ''
].join('\n')

writeFileSync(outputPath, output, 'utf-8')
console.log(`Generated MCP App HTML (${(html.length / 1024).toFixed(0)}KB) → src/mcp-app/generated-html.ts`)
