import { describe, expect, it } from 'vitest'
import { readFile, readdir } from 'node:fs/promises'
import { resolve, sep, posix } from 'node:path'
import { emitCubes } from '../../../src/cli/dbt/emit-cubes.js'
import { emitSchema } from '../../../src/cli/dbt/emit-schema.js'
import { normalizeDbtArtifacts } from '../../../src/cli/dbt/normalize.js'
import { loadDbtArtifacts } from '../../../src/cli/dbt/parse-artifacts.js'
import type { EmitContext, SecurityMode } from '../../../src/cli/dbt/types.js'

const FIXTURE_ROOT = resolve(__dirname, '../../fixtures/dbt/postgres-simple')
const EXPECTED_ROOT = resolve(FIXTURE_ROOT, 'expected')

const FILTER_SECURITY: SecurityMode = {
  kind: 'filter',
  columnName: 'organisation_id',
  contextProperty: 'organisationId',
}

const MANIFEST_PATH = 'tests/fixtures/dbt/postgres-simple/manifest.json'
const CATALOG_PATH = 'tests/fixtures/dbt/postgres-simple/catalog.json'

function makeContext(security: SecurityMode): EmitContext {
  return { manifestPath: MANIFEST_PATH, catalogPath: CATALOG_PATH, dialect: 'postgres', security }
}

/** Recursively collect expected fixture files as POSIX path → content. */
async function readExpectedFiles(): Promise<Map<string, string>> {
  const out = new Map<string, string>()
  async function walk(dir: string, relPrefix: string): Promise<void> {
    const entries = await readdir(dir, { withFileTypes: true })
    for (const entry of entries) {
      const full = resolve(dir, entry.name)
      const rel = relPrefix ? `${relPrefix}/${entry.name}` : entry.name
      if (entry.isDirectory()) {
        await walk(full, rel)
      } else {
        out.set(rel, await readFile(full, 'utf-8'))
      }
    }
  }
  await walk(EXPECTED_ROOT, '')
  return out
}

describe('emit (byte-for-byte against fixtures)', () => {
  it('emits schema.ts and cube files matching the expected fixture set', async () => {
    const artifacts = await loadDbtArtifacts(
      resolve(FIXTURE_ROOT, 'manifest.json'),
      resolve(FIXTURE_ROOT, 'catalog.json'),
    )
    const { models, warnings } = normalizeDbtArtifacts(artifacts, { security: FILTER_SECURITY })
    // The only expected warning is the skipped ephemeral model.
    expect(warnings.map((w) => w.code)).toEqual(['MODEL_SKIPPED'])
    expect(warnings[0].modelName).toBe('ephemeral_rollup')

    const context = makeContext(FILTER_SECURITY)
    const files = [emitSchema(models, context), ...emitCubes(models, context)]
    const generated = new Map(files.map((f) => [f.path, f.content]))

    const expected = await readExpectedFiles()

    // Every expected file must be generated byte-for-byte.
    for (const [path, content] of expected) {
      expect(generated.has(path), `expected file ${path} was not generated`).toBe(true)
      expect(generated.get(path)).toBe(content)
    }
    // No extra generated files beyond the expected set.
    for (const path of generated.keys()) {
      expect(expected.has(path), `unexpected generated file ${path}`).toBe(true)
    }
  })

  it('emits composite-PK cube with countDistinct (not count)', async () => {
    const artifacts = await loadDbtArtifacts(
      resolve(FIXTURE_ROOT, 'manifest.json'),
      resolve(FIXTURE_ROOT, 'catalog.json'),
    )
    const { models } = normalizeDbtArtifacts(artifacts, { security: FILTER_SECURITY })
    const orderLines = models.find((m) => m.cubeName === 'OrderLines')!
    const count = orderLines.measures.find((m) => m.name === 'count')!
    expect(count.type).toBe('countDistinct')
    expect(count.sql).toMatch(/^concat_ws:/)
    // Every PK column is marked primaryKey: true.
    const pkDims = orderLines.columns.filter((c) => c.primaryKey)
    expect(pkDims.map((c) => c.sqlName).sort()).toEqual(['line_number', 'order_id'])
  })

  it('emits cube code importing from drizzle-cube/server with non-generic public types', async () => {
    const artifacts = await loadDbtArtifacts(
      resolve(FIXTURE_ROOT, 'manifest.json'),
      resolve(FIXTURE_ROOT, 'catalog.json'),
    )
    const { models } = normalizeDbtArtifacts(artifacts, { security: FILTER_SECURITY })
    const files = emitCubes(models, makeContext(FILTER_SECURITY))
    const orders = files.find((f) => f.path === 'cubes/orders.ts')!.content
    expect(orders).toContain("from 'drizzle-cube/server'")
    // Non-generic public types (no <Schema> parameter).
    expect(orders).toContain('QueryContext')
    expect(orders).toContain('BaseQueryDefinition')
    expect(orders).not.toMatch(/QueryContext<.*>/)
    expect(orders).not.toMatch(/Cube<.*>/)
    // Direct Drizzle table/column references.
    expect(orders).toContain('Orders.id')
    expect(orders).toContain('Customers.id')
    // String target cube name (not a lazy arrow import).
    expect(orders).toContain("targetCube: 'Customers'")
  })

  it('emits a no-security variant with no where and a comment', async () => {
    const artifacts = await loadDbtArtifacts(
      resolve(FIXTURE_ROOT, 'manifest.json'),
      resolve(FIXTURE_ROOT, 'catalog.json'),
    )
    const noneSecurity: SecurityMode = { kind: 'none' }
    const { models } = normalizeDbtArtifacts(artifacts, { security: noneSecurity })
    const files = emitCubes(models, makeContext(noneSecurity))
    const customers = files.find((f) => f.path === 'cubes/customers.ts')!.content
    expect(customers).toContain('No cube-level security filter was requested')
    expect(customers).not.toMatch(/where:/)
    // sql returns a plain from, no ctx parameter usage binding security.
    expect(customers).toContain('sql: (): BaseQueryDefinition => ({')
  })
})

// Silence unused import warnings for posix/sep (kept for cross-platform path reasoning).
void posix
void sep
