import { mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { writeGeneratedFiles } from '../../../src/cli/dbt/write-output.js'

const files = [
  { path: 'schema.ts', content: '// Generated by drizzle-cube dbt generate.\nexport const x = 1\n' },
  { path: 'cubes/orders.ts', content: '// Generated by drizzle-cube dbt generate.\nexport const y = 1\n' },
]

async function tmp(): Promise<string> {
  return mkdtemp(join(tmpdir(), 'dbt-write-'))
}

describe('writeGeneratedFiles', () => {
  it('writes files and passes check when current', async () => {
    const dir = await tmp()
    const result = await writeGeneratedFiles(files, dir, {})
    expect(result.entries.map((entry) => entry.action)).toEqual(['create', 'create'])
    expect(await readFile(join(dir, 'schema.ts'), 'utf8')).toBe(files[0]!.content)
    await expect(writeGeneratedFiles(files, dir, { check: true })).resolves.toMatchObject({ current: true })
  })

  it('supports dry-run and failed check without writing', async () => {
    const dir = await tmp()
    const dryRun = await writeGeneratedFiles(files, dir, { dryRun: true })
    expect(dryRun.entries.map((entry) => entry.action)).toEqual(['create', 'create'])
    await expect(readFile(join(dir, 'schema.ts'), 'utf8')).rejects.toThrow()
    await expect(writeGeneratedFiles(files, dir, { check: true })).rejects.toThrow('Generated output is not current')
  })

  it('refuses non-generated overwrite unless force is set', async () => {
    const dir = await tmp()
    await writeFile(join(dir, 'schema.ts'), 'manual')
    await expect(writeGeneratedFiles(files, dir, {})).rejects.toThrow('Refusing to overwrite non-generated file')
    await expect(writeGeneratedFiles(files, dir, { force: true })).resolves.toBeDefined()
  })

  it('rejects path traversal', async () => {
    const dir = await tmp()
    await expect(writeGeneratedFiles([{ path: '../escape.ts', content: files[0]!.content }], dir, {})).rejects.toThrow('outside output directory')
  })
})
