// Generated by drizzle-cube dbt generate.
import { eq } from 'drizzle-orm'
import { defineCube } from 'drizzle-cube/server'
import type { BaseQueryDefinition, QueryContext } from 'drizzle-cube/server'
import { customers, orders } from '../schema.js'

export const ordersCube = defineCube("Orders", {
  title: "Orders",
  description: "Order fact model.",
  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: orders,
    where: eq(orders.organisationId, ctx.securityContext.organisationId)
  }),

  dimensions: {
    id: {
      name: "id",
      title: "Id",
      description: "Order identifier.",
      type: "number",
      sql: orders.id,
      primaryKey: true
    },
    customerId: {
      name: "customerId",
      title: "Customer Id",
      description: "Customer foreign key.",
      type: "number",
      sql: orders.customerId
    },
    organisationId: {
      name: "organisationId",
      title: "Organisation Id",
      description: "Tenant organisation identifier.",
      type: "number",
      sql: orders.organisationId
    },
    amount: {
      name: "amount",
      title: "Amount",
      description: "Order amount.",
      type: "number",
      sql: orders.amount
    },
    status: {
      name: "status",
      title: "Status",
      description: "Order status.",
      type: "string",
      sql: orders.status
    },
    orderedAt: {
      name: "orderedAt",
      title: "Ordered At",
      description: "Order timestamp.",
      type: "time",
      sql: orders.orderedAt
    },
  },

  measures: {
    count: {
      name: "count",
      title: "Count",
      type: "countDistinct",
      sql: orders.id
    },
    averageAmount: {
      name: "averageAmount",
      title: "Average Amount",
      type: "avg",
      sql: orders.amount
    },
    totalAmount: {
      name: "totalAmount",
      title: "Total Amount",
      type: "sum",
      sql: orders.amount,
      format: "currency"
    },
  },

  joins: {
    Customers: {
      targetCube: "Customers",
      relationship: "belongsTo",
      on: [
        { source: orders.customerId, target: customers.id }
      ]
    },
  },
})
