// Generated by drizzle-cube dbt generate.
import { customersCube } from './cubes/customers.js'
import { ordersCube } from './cubes/orders.js'

export { customersCube }
export { ordersCube }

export const allCubes = [customersCube, ordersCube]
