// Generated by drizzle-cube dbt generate.
// Source: manifest=tests/fixtures/dbt/postgres-simple/manifest.json, catalog=tests/fixtures/dbt/postgres-simple/catalog.json, dialect=postgres.
// Model: customers (table)

import { eq } from 'drizzle-orm'
import { defineCube } from 'drizzle-cube/server'
import type { QueryContext, BaseQueryDefinition } from 'drizzle-cube/server'
import { Customers } from '../schema.js'

export const customersCube = defineCube('Customers', {
  title: "Customers",
  description: "Customer dimension table.",

  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: Customers,
    where: eq(Customers.organisationId, ctx.securityContext.organisationId as number)
  }),

  dimensions: {
    id: {
      name: 'id',
      title: "ID",
      description: "Customer identifier.",
      type: 'number',
      sql: Customers.id,
      primaryKey: true,
    },
    organisationId: {
      name: 'organisationId',
      title: "Organisation ID",
      description: "Tenant isolation column.",
      type: 'number',
      sql: Customers.organisationId,
    },
    name: {
      name: 'name',
      title: "Name",
      description: "Customer display name.",
      type: 'string',
      sql: Customers.name,
    },
    status: {
      name: 'status',
      title: "Status",
      description: "Customer status.",
      type: 'string',
      sql: Customers.status,
    },
    createdAt: {
      name: 'createdAt',
      title: "Created At",
      description: "Customer creation timestamp.",
      type: 'time',
      sql: Customers.createdAt,
    },
  },

  measures: {
    count: {
      name: 'count',
      title: "Count",
      type: 'countDistinct',
      sql: Customers.id,
    },
  },
})
