// Generated by drizzle-cube dbt generate.

import { eq } from 'drizzle-orm'
import { defineCube, type BaseQueryDefinition, type Cube, type QueryContext } from 'drizzle-cube/server'
import { customers } from '../schema.js'

function securityValue(ctx: QueryContext): number {
  const value = ctx.securityContext.organisationId
  if (typeof value !== 'number') {
    throw new Error('Missing number security context value \'organisationId\'.')
  }
  return value
}

export const CustomersCube: Cube = defineCube('Customers', {
  title: 'Customers',
  description: 'Customer records.\nOne row per customer, including O\'Hare\'s accounts.',
  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: customers,
    where: eq(customers.organisationId, securityValue(ctx))
  }),
  dimensions: {
    id: {
      name: 'id',
      title: 'Id',
      description: 'Customer id.',
      type: 'number',
      sql: customers.id,
      primaryKey: true
    },
    organisationId: {
      name: 'organisationId',
      title: 'Organisation Id',
      description: 'Tenant id.',
      type: 'number',
      sql: customers.organisationId
    },
    name: {
      name: 'name',
      title: 'Name',
      description: 'Customer name.',
      type: 'string',
      sql: customers.name
    },
    active: {
      name: 'active',
      title: 'Active',
      description: 'Whether the customer is active.',
      type: 'boolean',
      sql: customers.active
    },
    signedUpAt: {
      name: 'signedUpAt',
      title: 'Signed Up At',
      description: 'Signup time.',
      type: 'time',
      sql: customers.signedUpAt
    },
    externalRef: {
      name: 'externalRef',
      title: 'External Ref',
      description: 'CRM reference.',
      type: 'string',
      sql: customers.externalRef
    },
    parentCustomerId: {
      name: 'parentCustomerId',
      title: 'Parent Customer Id',
      description: 'Parent account.',
      type: 'number',
      sql: customers.parentCustomerId
    }
  },
  measures: {
    count: {
      name: 'count',
      type: 'countDistinct',
      sql: customers.id
    }
  }
})
