// Generated by drizzle-cube dbt generate.
// Source: manifest=target/manifest.json, catalog=target/catalog.json, dialect=postgres.
// Do not edit manually; change dbt metadata or generator config instead.

import { eq } from 'drizzle-orm'
import { defineCube } from 'drizzle-cube/server'
import type { QueryContext, BaseQueryDefinition } from 'drizzle-cube/server'
import { customers } from '../schema.js'

export const customersCube = defineCube('Customers', {
  title: 'Customers',

  description: 'One row per customer.',

  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: customers,
    where: eq(customers.organisationId, ctx.securityContext.organisationId as number)
  }),

  dimensions: {
    fullName: {
      name: 'fullName',
      title: 'Full Name',
      type: 'string',
      sql: customers.fullName,
      description: 'Customer\'s full name.'
    },
    id: {
      name: 'id',
      title: 'Id',
      type: 'number',
      sql: customers.id,
      primaryKey: true,
      description: 'Surrogate key for the customer.'
    },
    organisationId: {
      name: 'organisationId',
      title: 'Organisation Id',
      type: 'number',
      sql: customers.organisationId,
      description: 'Owning organisation.'
    }
  },

  measures: {
    count: {
      name: 'count',
      title: 'Count',
      type: 'countDistinct',
      sql: customers.id
    }
  }
})
