// Generated by drizzle-cube dbt generate.

import { eq, sql } from 'drizzle-orm'
import { defineCube, type BaseQueryDefinition, type Cube, type QueryContext } from 'drizzle-cube/server'
import { orderLines, orders } from '../schema.js'

function securityValue(ctx: QueryContext): number {
  const value = ctx.securityContext.organisationId
  if (typeof value !== 'number') {
    throw new Error('Missing number security context value \'organisationId\'.')
  }
  return value
}

export const OrderLinesCube: Cube = defineCube('OrderLines', {
  title: 'Order Lines',
  description: 'One row per order line.',
  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: orderLines,
    where: eq(orderLines.organisationId, securityValue(ctx))
  }),
  dimensions: {
    orderId: {
      name: 'orderId',
      title: 'Order Id',
      description: 'Order.',
      type: 'number',
      sql: orderLines.orderId,
      primaryKey: true
    },
    lineNumber: {
      name: 'lineNumber',
      title: 'Line Number',
      description: 'Line within the order.',
      type: 'number',
      sql: orderLines.lineNumber,
      primaryKey: true
    },
    organisationId: {
      name: 'organisationId',
      title: 'Organisation Id',
      description: 'Tenant id.',
      type: 'number',
      sql: orderLines.organisationId
    },
    count: {
      name: 'count',
      title: 'Count',
      description: 'Units on the line.',
      type: 'number',
      sql: orderLines.count
    }
  },
  measures: {
    count2: {
      name: 'count2',
      type: 'countDistinct',
      sql: sql<string>`concat_ws('|', ${orderLines.orderId}, ${orderLines.lineNumber})`
    }
  },
  joins: {
    orders: {
      targetCube: 'Orders',
      relationship: 'belongsTo',
      on: [{ source: orderLines.orderId, target: orders.id }]
    }
  }
})
