// Generated by drizzle-cube dbt generate.
// Source: manifest=tests/fixtures/dbt/postgres-simple/manifest.json, catalog=tests/fixtures/dbt/postgres-simple/catalog.json, dialect=postgres.
// Model: orders (table)

import { eq } from 'drizzle-orm'
import { defineCube } from 'drizzle-cube/server'
import type { QueryContext, BaseQueryDefinition } from 'drizzle-cube/server'
import { Orders, Customers } from '../schema.js'

export const ordersCube = defineCube('Orders', {
  title: "Orders",
  description: "Customer orders fact table.",

  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: Orders,
    where: eq(Orders.organisationId, ctx.securityContext.organisationId as number)
  }),

  joins: {
    Customers: {
      targetCube: 'Customers',
      relationship: 'belongsTo',
      on: [{ source: Orders.customerId, target: Customers.id }],
    },
  },

  dimensions: {
    id: {
      name: 'id',
      title: "ID",
      description: "Order identifier.",
      type: 'number',
      sql: Orders.id,
      primaryKey: true,
    },
    organisationId: {
      name: 'organisationId',
      title: "Organisation ID",
      description: "Tenant isolation column.",
      type: 'number',
      sql: Orders.organisationId,
    },
    customerId: {
      name: 'customerId',
      title: "Customer ID",
      description: "FK to customers.",
      type: 'number',
      sql: Orders.customerId,
    },
    amount: {
      name: 'amount',
      title: "Amount",
      description: "Order total in cents.",
      type: 'number',
      sql: Orders.amount,
    },
    status: {
      name: 'status',
      title: "Status",
      description: "Order lifecycle status.",
      type: 'string',
      sql: Orders.status,
    },
    createdAt: {
      name: 'createdAt',
      title: "Created At",
      description: "Order creation timestamp.",
      type: 'time',
      sql: Orders.createdAt,
    },
    active: {
      name: 'active',
      title: "Active",
      description: "Whether the order is active.",
      type: 'boolean',
      sql: Orders.active,
    },
  },

  measures: {
    count: {
      name: 'count',
      title: "Count",
      type: 'countDistinct',
      sql: Orders.id,
    },
    totalAmount: {
      name: 'totalAmount',
      title: "Total Amount",
      type: 'sum',
      sql: Orders.amount,
      format: 'currency',
    },
  },
})
