// Generated by drizzle-cube dbt generate.
// Source: manifest=manifest.json catalog=catalog.json dialect=postgres
// To regenerate, run: npx drizzle-cube dbt generate --manifest manifest.json --catalog catalog.json --dialect postgres

import { eq, sql } from 'drizzle-orm'
import { defineCube } from 'drizzle-cube/server'
import type { QueryContext, BaseQueryDefinition } from 'drizzle-cube/server'
import { OrderLines } from '../schema.js'

export const orderLinesCube = defineCube('OrderLines', {
  title: "Order Lines",
  description: "Line items for orders (composite primary key).",
  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: OrderLines,
    where: eq(OrderLines.organisationId, ctx.securityContext.organisationId as number),
  }),

  dimensions: {
    orderId: {
      name: 'orderId',
      title: "Order ID",
      description: "Composite PK part 1.",
      type: 'number',
      sql: OrderLines.orderId,
      primaryKey: true,
    },
    lineNumber: {
      name: 'lineNumber',
      title: "Line Number",
      description: "Composite PK part 2.",
      type: 'number',
      sql: OrderLines.lineNumber,
      primaryKey: true,
    },
    organisationId: {
      name: 'organisationId',
      title: "Organisation ID",
      description: "Tenant scope.",
      type: 'number',
      sql: OrderLines.organisationId,
    },
    quantity: {
      name: 'quantity',
      title: "Quantity",
      type: 'number',
      sql: OrderLines.quantity,
    },
    sku: {
      name: 'sku',
      title: "SKU",
      type: 'string',
      sql: OrderLines.sku,
    },
    amount: {
      name: 'amount',
      title: "Amount",
      type: 'number',
      sql: OrderLines.amount,
    },
    createdAt: {
      name: 'createdAt',
      title: "Created At",
      type: 'time',
      sql: OrderLines.createdAt,
    },
  },

  measures: {
    count: {
      name: 'count',
      title: "Count",
      type: 'countDistinct',
      sql: sql`concat_ws('|', ${OrderLines.orderId}, ${OrderLines.lineNumber})`,
    },
  },
})
