// Generated by drizzle-cube dbt generate.
// Source: manifest=tests/fixtures/dbt/postgres-simple/manifest.json, catalog=tests/fixtures/dbt/postgres-simple/catalog.json, dialect=postgres.
// Model: order_lines (table)

import { eq, sql } from 'drizzle-orm'
import { defineCube } from 'drizzle-cube/server'
import type { QueryContext, BaseQueryDefinition } from 'drizzle-cube/server'
import { OrderLines } from '../schema.js'

export const orderLinesCube = defineCube('OrderLines', {
  title: "Order Lines",
  description: "Order line items with a composite primary key.",

  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: OrderLines,
    where: eq(OrderLines.organisationId, ctx.securityContext.organisationId as number)
  }),

  dimensions: {
    orderId: {
      name: 'orderId',
      title: "Order ID",
      description: "FK to orders.",
      type: 'number',
      sql: OrderLines.orderId,
      primaryKey: true,
    },
    lineNumber: {
      name: 'lineNumber',
      title: "Line Number",
      description: "Line number within an order.",
      type: 'number',
      sql: OrderLines.lineNumber,
      primaryKey: true,
    },
    organisationId: {
      name: 'organisationId',
      title: "Organisation ID",
      description: "Tenant isolation column.",
      type: 'number',
      sql: OrderLines.organisationId,
    },
    quantity: {
      name: 'quantity',
      title: "Quantity",
      description: "Line item quantity.",
      type: 'number',
      sql: OrderLines.quantity,
    },
    sku: {
      name: 'sku',
      title: "SKU",
      description: "Product SKU.",
      type: 'string',
      sql: OrderLines.sku,
    },
    createdAt: {
      name: 'createdAt',
      title: "Created At",
      description: "Line creation timestamp.",
      type: 'time',
      sql: OrderLines.createdAt,
    },
  },

  measures: {
    count: {
      name: 'count',
      title: "Count",
      type: 'countDistinct',
      sql: sql`count(distinct concat_ws('|', OrderLines.orderId, OrderLines.lineNumber))`,
    },
  },
})
