// Generated by drizzle-cube dbt generate.
// Source: manifest=manifest.json catalog=catalog.json dialect=postgres
// To regenerate, run: npx drizzle-cube dbt generate --manifest manifest.json --catalog catalog.json --dialect postgres

import { eq } from 'drizzle-orm'
import { defineCube } from 'drizzle-cube/server'
import type { QueryContext, BaseQueryDefinition } from 'drizzle-cube/server'
import { Customers, Orders } from '../schema.js'

export const ordersCube = defineCube('Orders', {
  title: "Orders",
  description: "Customer orders.",
  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: Orders,
    where: eq(Orders.organisationId, ctx.securityContext.organisationId as number),
  }),

  dimensions: {
    id: {
      name: 'id',
      title: "ID",
      description: "Order primary key.",
      type: 'number',
      sql: Orders.id,
      primaryKey: true,
    },
    organisationId: {
      name: 'organisationId',
      title: "Organisation ID",
      description: "Tenant scope.",
      type: 'number',
      sql: Orders.organisationId,
    },
    customerId: {
      name: 'customerId',
      title: "Customer ID",
      description: "References customers.id.",
      type: 'number',
      sql: Orders.customerId,
    },
    amount: {
      name: 'amount',
      title: "Amount",
      description: "Order total.",
      type: 'number',
      sql: Orders.amount,
    },
    status: {
      name: 'status',
      title: "Status",
      type: 'string',
      sql: Orders.status,
    },
    createdAt: {
      name: 'createdAt',
      title: "Created At",
      type: 'time',
      sql: Orders.createdAt,
    },
    active: {
      name: 'active',
      title: "Active",
      type: 'boolean',
      sql: Orders.active,
    },
  },

  measures: {
    count: {
      name: 'count',
      title: "Count",
      type: 'countDistinct',
      sql: Orders.id,
    },
    totalAmount: {
      name: 'totalAmount',
      title: "Total Amount",
      type: 'sum',
      sql: Orders.amount,
      description: "Sum of order amounts.",
      format: 'currency',
    },
  },

  joins: {
    Customers: {
      targetCube: 'Customers',
      relationship: 'belongsTo',
      on: [
      { source: Orders.customerId, target: Customers.id },
      ],
    },
  },
})
