// Generated by drizzle-cube dbt generate.

import { eq } from 'drizzle-orm'
import { defineCube, type BaseQueryDefinition, type Cube, type QueryContext } from 'drizzle-cube/server'
import { customers, orders } from '../schema'

function securityValue(ctx: QueryContext): number {
  const value = ctx.securityContext.organisationId
  if (typeof value !== 'number') {
    throw new Error('Missing number security context value \'organisationId\'.')
  }
  return value
}

export const OrdersCube: Cube = defineCube('Orders', {
  title: 'Orders',
  description: 'Order facts.',
  sql: (ctx: QueryContext): BaseQueryDefinition => ({
    from: orders,
    where: eq(orders.organisationId, securityValue(ctx))
  }),
  dimensions: {
    id: {
      name: 'id',
      title: 'Id',
      description: 'Order id.',
      type: 'number',
      sql: orders.id,
      primaryKey: true
    },
    organisationId: {
      name: 'organisationId',
      title: 'Organisation Id',
      description: 'Tenant id.',
      type: 'number',
      sql: orders.organisationId
    },
    customerId: {
      name: 'customerId',
      title: 'Customer Id',
      description: 'Customer id.',
      type: 'number',
      sql: orders.customerId
    },
    status: {
      name: 'status',
      title: 'Status',
      description: 'Order status.',
      type: 'string',
      sql: orders.status
    },
    amount: {
      name: 'amount',
      title: 'Amount',
      description: 'Order amount.',
      type: 'number',
      sql: orders.amount
    },
    createdAt: {
      name: 'createdAt',
      title: 'Created At',
      description: 'Creation timestamp.',
      type: 'time',
      sql: orders.createdAt
    }
  },
  measures: {
    count: {
      name: 'count',
      type: 'countDistinct',
      sql: orders.id
    },
    totalAmount: {
      name: 'totalAmount',
      type: 'sum',
      sql: orders.amount,
      title: 'Total Amount'
    }
  },
  joins: {
    customers: {
      targetCube: 'Customers',
      relationship: 'belongsTo',
      on: [{ source: orders.customerId, target: customers.id }]
    }
  }
})
